### ISSUE TITLE
Shutting down takes too much time

### ISSUE THREAD

**Issue by louisroyer** [free5gc/nrf#33]
https://github.com/free5gc/nrf/blob/21c66562cdfb4eca576a6bdd3d5feb9a06bc2061/pkg/service/init.go#L111-L112

Instead of only waiting 2s for NFs to deregister, it would be better to exit as soon as every NF is de-registered (which takes usually less time than 2 seconds), with a Timeout at 2 seconds. This would make shutdown faster.

It would also be better to Drop NfProfile with a short timeout. This would allow to stop database before NRF (useful when database container volume is not saved anyway, for example when using Free5GC for development purposes) : https://github.com/free5gc/util/blob/42899f4954697dd88099c61768b802b5d7b8e96d/mongoapi/mongoapi.go#L325

**Comment by andy89923** [comment]
Thanks for your advice. This performance improvement was done in https://github.com/free5gc/nrf/pull/42/commits/359333a8a840861007a4ddbe295b1c6f61b2630a and PR #42.
